version: "3.9"

services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"

    volumes:
      - ./mlruns:/home/mlflow/mlruns
      - ./mlartifacts:/home/mlflow/mlartifacts

